### PR TITLE
added proposed sections to expand upon

### PR DESCRIPTION
**Pull request by aleon1220**
@robzienert Hi,
i have a stateful set running maria DB i set my orca-local.yaml and i wonder if this driver would improve the behaviour of orca and spinnaker overall. It would be great to have some extra details on how to set up the driver. I am happy to help.

added intro
build
Use drive in Spinnaker

### CODE REVIEW

**Comment by robzienert** [comment]
I don't plan to expand on this repo. It would probably make more sense being re-written as a plugin. All this said, Netflix abandoned the MariaDB driver in favor of the vanilla mysql connectorj driver because MariaDB's Aurora code is actually quite awful and no longer needed with improvements made to Aurora over the last couple years.

**Comment by robzienert** [comment]
I will accept this PR if there's more put into it.

**Comment by aleon1220** [comment]
> I don't plan to expand on this repo. It would probably make more sense being re-written as a plugin. All this said, Netflix abandoned the MariaDB driver in favor of the vanilla mysql connectorj driver because MariaDB's Aurora code is actually quite awful and no longer needed with improvements made to Aurora over the last couple years.

oh thanks. Should your readme.md contain this:
```
Netflix abandoned the MariaDB driver in favor of the vanilla mysql connectorj driver because MariaDB's Aurora code is actually quite awful and no longer needed with improvements made to Aurora over the last couple years.
```

the Spinnaker.io site [Orca SQL page](https://www.spinnaker.io/setup/productionize/persistence/orca-sql/#mariadb) points to your repo.
looking forward to help in some form.

**Comment by robzienert** [comment]
In order to use this, you would need to build a custom version of clouddriver. The general process for that is covered in this blog post: https://blog.spinnaker.io/scaling-spinnaker-at-netflix-custom-features-and-packaging-e78536d38040

If this were re-written as a plugin, you could just drop the plugin into a directory and it would be loaded automatically.

**Comment by aleon1220** [comment]
Thanks a lot for your response. Sounds like an interesting project with intermediate level of complexity. Thanks

**Pull request closed without merging**
